# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GrowIT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GrowIT
  pod 'Then'
  pod 'SnapKit', '~> 5.7.0'
  pod 'Alamofire'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'lottie-ios'
  pod 'NVActivityIndicatorView'
  pod 'SwiftyToaster'

end
